# Generated by Django 2.1.7 on 2019-03-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField()),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('fm_radio', models.TextField()),
                ('torch', models.DateField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('operating_system', models.TextField()),
                ('screen_matrix', models.DateField()),
                ('cpu', models.TextField()),
                ('ram', models.TextField()),
            ],
            bases=('phones.phone',),
        ),
    ]
