# Generated by Django 2.1.7 on 2019-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='torch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_matrix',
            field=models.TextField(),
        ),
    ]
