# Generated by Django 2.1.7 on 2019-03-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190330_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Тематики статьи'},
        ),
    ]
