# Generated by Django 2.1.7 on 2019-03-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190330_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='delete_checkbox',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='main',
        ),
        migrations.AddField(
            model_name='relationship',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Tag', verbose_name='Раздел'),
        ),
    ]
