# Generated by Django 2.1.7 on 2019-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190331_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='section',
            field=models.TextField(),
        ),
    ]
