# Generated by Django 2.2 on 2019-04-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathToFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=300, path='.', verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Путь к файлу',
                'verbose_name_plural': 'Путь к файлу',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.FloatField(max_length=50, verbose_name='Цена')),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('ordinal', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Наименование поля',
                'verbose_name_plural': 'Наименования полей',
                'ordering': ['ordinal'],
            },
        ),
    ]
