# Generated by Django 2.2 on 2019-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20190417_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesettings',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
