# Generated by Django 2.2 on 2019-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20190417_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathtofile',
            name='path',
            field=models.FilePathField(max_length=300),
        ),
    ]
