# Generated by Django 2.2 on 2019-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20190417_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathtofile',
            name='path',
            field=models.FilePathField(max_length=300, path='/'),
        ),
    ]
