# Generated by Django 2.2 on 2019-04-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='guess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_player', to='game.Player'),
        ),
    ]
