# Generated by Django 2.2 on 2019-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190409_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='is_guessed',
            field=models.BooleanField(default=False),
        ),
    ]
